
CHIP_FLAGS += -D DEVICE_TERMINAL_NS16550A

INCLUDES  += -I$(DRIVER_DIR)national-semiconductor/ns16550a
A_SOURCES += $(DRIVER_DIR)national-semiconductor/ns16550a/ns16550a.S
C_SOURCES += $(DRIVER_DIR)national-semiconductor/ns16550a/uart.c