
INCLUDES  += -I$(DRIVER_DIR)rocket-chip-blocks/gpio/
INCLUDES  += -I$(DRIVER_DIR)rocket-chip-blocks/uart/
C_SOURCES += $(DRIVER_DIR)rocket-chip-blocks/gpio/hal_gpio.c
C_SOURCES += $(DRIVER_DIR)rocket-chip-blocks/uart/hal_uart.c
