INCLUDES  += -I$(DRIVER_DIR)rocket-chip/clint/
INCLUDES  += -I$(DRIVER_DIR)rocket-chip/plic/
C_SOURCES += $(DRIVER_DIR)rocket-chip/clint/hal_clint.c
C_SOURCES += $(DRIVER_DIR)rocket-chip/plic/hal_plic.c
