CHIP_FLAGS += -DDEVICE_TIME_CLINT

INCLUDES  += -I$(DRIVER_DIR)rocket-chip/clint/
INCLUDES  += -I$(DRIVER_DIR)rocket-chip/plic/
INCLUDES  += -I$(DRIVER_DIR)rocket-chip/rocketcore/
C_SOURCES += $(DRIVER_DIR)rocket-chip/clint/clint.c
C_SOURCES += $(DRIVER_DIR)rocket-chip/plic/plic.c
C_SOURCES += $(DRIVER_DIR)rocket-chip/rocketcore/rocketcore.c