
ARCH 		= rv32imac
ABI 		= ilp32
CODEMODEL 	= medany

include $(DRIVER_DIR)rv/Makefile

include $(DRIVER_DIR)rocket-chip/Makefile
include $(DRIVER_DIR)rocket-chip-blocks/Makefile

include $(LIB_DIR)standalone/Makefile