
ARCH 		= rv64imafc
ABI 		= lp64f
CODEMODEL 	= medany

include $(DRIVER_DIR)rv/Makefile

include $(DRIVER_DIR)rocket-chip/Makefile
include $(DRIVER_DIR)rocket-chip-blocks/Makefile

include $(LIB_DIR)standalone/Makefile