
ARCH 		= rv64imafdc
ABI 		= lp64d
CODEMODEL 	= medany

### Driver Sources ###
include $(DRIVER_DIR)rv/Makefile

include $(DRIVER_DIR)rocket-chip/Makefile
include $(DRIVER_DIR)rocket-chip-blocks/Makefile

### Lib Sources ###
include $(LIB_DIR)htif/Makefile
