
INCLUDES  += -I$(LIB_DIR)syscall/

C_SOURCES += $(LIB_DIR)syscall/close.c
C_SOURCES += $(LIB_DIR)syscall/exit.c
C_SOURCES += $(LIB_DIR)syscall/fstat.c
C_SOURCES += $(LIB_DIR)syscall/getpid.c
C_SOURCES += $(LIB_DIR)syscall/isatty.c
C_SOURCES += $(LIB_DIR)syscall/kill.c
C_SOURCES += $(LIB_DIR)syscall/lseek.c
C_SOURCES += $(LIB_DIR)syscall/read.c
C_SOURCES += $(LIB_DIR)syscall/sbrk.c
C_SOURCES += $(LIB_DIR)syscall/time.c
C_SOURCES += $(LIB_DIR)syscall/write.c

